FROM python:3.12.4-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN rm ./requirements.txt

COPY src ./src
COPY tests ./tests

ENTRYPOINT ["pytest"]
CMD ["--color=yes", "tests/"]