FROM python:3.12.4-slim

WORKDIR /app

RUN pip install mypy

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN rm ./requirements.txt

COPY src ./src

ENTRYPOINT ["mypy"]
CMD ["src", "--enable-incomplete-feature=NewGenericSyntax"]