FROM python:3.12.4-slim

WORKDIR /app

RUN pip install mypy

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN rm ./requirements.txt

COPY src ./src

ENV TERM=ansi
ENV MYPY_FORCE_COLOR=1

ENTRYPOINT ["mypy"]
CMD ["src", "--strict", "--enable-incomplete-feature=NewGenericSyntax"]