name: MyPy tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Build Docker container with MyPy tests
      run: docker build -t mypy-tests -f Dockerfile.mypy .
    - name: Run MyPy tests
      run: docker run mypy-tests
